import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { AppShell } from "@/components/app-shell";
import {
  Baby, Cake, CalendarDays, Check, ChevronLeft, ChevronRight, Flower2,
  GraduationCap, Heart, MapPin, MoonStar, Pencil, Plus, Sparkles,
  Trash2, Trophy, Users, X, ShieldPlus,
} from "lucide-react";

export const Route = createFileRoute("/_authenticated/family-occasions")({
  ssr: false,
  head: () => ({ meta: [
    { title: "مناسبات العائلة — السيف" },
    { name: "description", content: "مناسبات العائلة ودعواتها في مكان واحد." },
  ] }),
  component: FamilyOccasionsPage,
});

type OccasionType = "wedding" | "newborn" | "condolence" | "graduation" | "birthday" | "promotion" | "recovery" | "gathering" | "ramadan" | "eid_fitr" | "eid_adha";
type BirthdayAudience = "adult" | "child";
type Occasion = { id:string; type:OccasionType; design:number; title:string; date:string; time:string; location:string; details:string; birthDate?:string; birthdayAudience?:BirthdayAudience };
type OccasionTypeMeta = { key:OccasionType; title:string; icon:typeof Heart; designs:number };

const TYPE_OPTIONS: OccasionTypeMeta[] = [
  { key:"wedding", title:"زواج / ملكة", icon:Heart, designs:3 },
  { key:"newborn", title:"مولود", icon:Baby, designs:3 },
  { key:"graduation", title:"تخرج", icon:GraduationCap, designs:3 },
  { key:"condolence", title:"عزاء", icon:Flower2, designs:1 },
  { key:"birthday", title:"يوم ميلاد", icon:Cake, designs:3 },
  { key:"promotion", title:"ترقية / إنجاز", icon:Trophy, designs:3 },
  { key:"recovery", title:"شفاء / سلامة", icon:ShieldPlus, designs:3 },
  { key:"gathering", title:"عزيمة / لمة عائلية", icon:Users, designs:3 },
  { key:"ramadan", title:"رمضان", icon:MoonStar, designs:3 },
  { key:"eid_fitr", title:"عيد الفطر", icon:Sparkles, designs:3 },
  { key:"eid_adha", title:"عيد الأضحى", icon:MoonStar, designs:3 },
];

const STORAGE_KEY = "alsaif:family-occasions";
const FAMILY_MARK = "السيف";
function getTypeMeta(type:OccasionType){ return TYPE_OPTIONS.find(x=>x.key===type) ?? TYPE_OPTIONS[0]; }
function designCount(type:OccasionType){ return getTypeMeta(type).designs; }
function buildDefaultTitle(type:OccasionType){
  const labels:Record<OccasionType,string>={ wedding:"دعوة زواج", newborn:"بشارة مولود", condolence:"تعزية", graduation:"حفل تخرج", birthday:"يوم ميلاد", promotion:"مبارك الترقية والإنجاز", recovery:"سلامتك هي فرحتنا", gathering:"لمتنا سر السعادة", ramadan:"رمضان مبارك", eid_fitr:"عيد فطر مبارك", eid_adha:"عيد أضحى مبارك" };
  return labels[type];
}
function calcAge(birthDate?:string,eventDate?:string){ if(!birthDate)return null; const b=new Date(`${birthDate}T12:00:00`), a=eventDate?new Date(`${eventDate}T12:00:00`):new Date(); if(Number.isNaN(b.getTime())||Number.isNaN(a.getTime()))return null; let age=a.getFullYear()-b.getFullYear(); const m=a.getMonth()-b.getMonth(); if(m<0||(m===0&&a.getDate()<b.getDate()))age--; return Math.max(0,age); }

function FamilyLogo({dark=false}:{dark?:boolean}){
  return <div className={`mx-auto grid size-10 place-items-center rounded-full border bg-white/10 text-[10px] font-black backdrop-blur ${dark?"border-[#c9a95f]/70 text-[#e4c978]":"border-[#b7974e]/40 text-[#0d5b4b]"}`}>{FAMILY_MARK}</div>;
}

type Recipe={ bg:string; fg:string; accent:string; symbol:string; kicker:string; decor:"rings"|"box"|"floral"|"baby"|"cloud"|"cradle"|"cap"|"certificate"|"medal"|"cake"|"number"|"balloons"|"trophy"|"desk"|"shield"|"leaves"|"light"|"minimal"|"coffee"|"table"|"night"|"moon"|"lantern"|"gifts"|"sheep"|"desert"|"black" };
function recipe(type:OccasionType, design:number, audience:BirthdayAudience, age:number|null):Recipe{
  const cream="#fbf7ed", green="#064d3f", gold="#c8a45e", navy="#102234", blush="#fff1ed", blue="#eaf4f6", sand="#efe0bd";
  if(type==="wedding") return design===1?{bg:`linear-gradient(145deg,#f8efe0 0%,${cream} 55%,#ede0c5 100%)`,fg:"#184d42",accent:gold,symbol:"💍",kicker:"تراث العائلة",decor:"rings"}:design===2?{bg:`radial-gradient(circle at 50% 90%,#163e34 0%,${green} 46%,#022f27 100%)`,fg:"#fff7df",accent:gold,symbol:"💍",kicker:"فخامة العائلة",decor:"box"}:{bg:`linear-gradient(160deg,#fffdf8 0%,#f4f0e5 100%)`,fg:"#164f43",accent:gold,symbol:"♡",kicker:"أناقة هادئة",decor:"floral"};
  if(type==="newborn") return design===1?{bg:`linear-gradient(160deg,#fffdf7,#eee6d3)`,fg:"#17584a",accent:gold,symbol:"🧸",kicker:"بشارة العائلة",decor:"baby"}:design===2?{bg:`linear-gradient(160deg,${blush},#fffaf6)`,fg:"#6f5147",accent:"#c69a6b",symbol:"☁",kicker:"فرحة ناعمة",decor:"cloud"}:{bg:`linear-gradient(160deg,#edf5ef,#fbf8ed)`,fg:"#17584a",accent:gold,symbol:"⌒",kicker:"مهد البشارة",decor:"cradle"};
  if(type==="graduation") return design===1?{bg:`linear-gradient(150deg,#fbf8ef,#e9e2cf)`,fg:"#0c5547",accent:gold,symbol:"🎓",kicker:"بداية الطريق",decor:"cap"}:design===2?{bg:`linear-gradient(150deg,#123d34,#052f28)`,fg:"#fff8e5",accent:gold,symbol:"▣",kicker:"إنجاز مستحق",decor:"certificate"}:{bg:`linear-gradient(150deg,#f9f7f1,#ece7da)`,fg:"#173f38",accent:gold,symbol:"✦",kicker:"حصاد التميز",decor:"medal"};
  if(type==="birthday" && audience==="child") return design===1?{bg:`linear-gradient(150deg,#fff8df,#eef8f2)`,fg:"#17634f",accent:"#e1ad4d",symbol:"🎂",kicker:"يوم فرح صغير",decor:"cake"}:design===2?{bg:`linear-gradient(150deg,#eaf6f7,#fff6df)`,fg:"#1b5460",accent:"#d5a33c",symbol:String(age??5),kicker:"سنة أجمل",decor:"number"}:{bg:`linear-gradient(150deg,#f4ecff,#e7f7f6)`,fg:"#4c4168",accent:"#d29b54",symbol:"🎈",kicker:"ذكرى طفولية",decor:"balloons"};
  if(type==="birthday") return design===1?{bg:`linear-gradient(150deg,#fcf7ec,#eee4cf)`,fg:"#164f42",accent:gold,symbol:"🎂",kicker:"احتفال عائلي",decor:"cake"}:design===2?{bg:`linear-gradient(150deg,#0b493d,#032f29)`,fg:"#fff5dc",accent:gold,symbol:String(age??"—"),kicker:"لحظة العمر",decor:"number"}:{bg:`linear-gradient(150deg,#fffdf8,#ece8de)`,fg:"#253d37",accent:gold,symbol:"✦",kicker:"ذكرى جميلة",decor:"balloons"};
  if(type==="promotion") return design===1?{bg:`linear-gradient(150deg,#063f35,#022d27)`,fg:"#fff6dc",accent:gold,symbol:"🏆",kicker:"إنجاز نفخر به",decor:"trophy"}:design===2?{bg:`linear-gradient(150deg,#fcfaf4,#e8e4da)`,fg:"#164f42",accent:gold,symbol:"✦",kicker:"ترقية مستحقة",decor:"desk"}:{bg:`linear-gradient(150deg,#171717,#292929)`,fg:"#fff8e7",accent:gold,symbol:"◆",kicker:"درع الإنجاز",decor:"shield"};
  if(type==="recovery") return design===1?{bg:`linear-gradient(150deg,#fffdf6,#eef2e7)`,fg:"#225c4d",accent:gold,symbol:"❧",kicker:"دعواتنا لك",decor:"leaves"}:design===2?{bg:`radial-gradient(circle at 50% 5%,#fff7d6,#f4ead5 48%,#e7ddc9)`,fg:"#285548",accent:gold,symbol:"✧",kicker:"نور العافية",decor:"light"}:{bg:`linear-gradient(150deg,#fffdfa,#f0eee8)`,fg:"#245247",accent:gold,symbol:"♡",kicker:"سلامتك فرحتنا",decor:"minimal"};
  if(type==="gathering") return design===1?{bg:`linear-gradient(150deg,#ead6b8,#f7ead8)`,fg:"#684126",accent:"#a8753e",symbol:"☕",kicker:"لمة دافئة",decor:"coffee"}:design===2?{bg:`linear-gradient(150deg,#f8f5ec,#e8eee6)`,fg:"#285348",accent:gold,symbol:"❧",kicker:"لمتنا سعادة",decor:"table"}:{bg:`linear-gradient(150deg,#0c2031,#061520)`,fg:"#fff4dc",accent:gold,symbol:"✦",kicker:"ليالي المحبة",decor:"night"};
  if(type==="ramadan") return design===1?{bg:`linear-gradient(160deg,#073d34,#021f1b)`,fg:"#fff5d4",accent:gold,symbol:"☾",kicker:"شهر الخير",decor:"lantern"}:design===2?{bg:`linear-gradient(160deg,#fffaf0,#eee6d4)`,fg:"#155044",accent:gold,symbol:"☾",kicker:"رمضان يجمعنا",decor:"moon"}:{bg:`linear-gradient(160deg,#102032,#07111d)`,fg:"#fff0c8",accent:gold,symbol:"☾",kicker:"ليالي رمضان",decor:"night"};
  if(type==="eid_fitr") return design===1?{bg:`linear-gradient(160deg,#f7f8ed,#e6efe7)`,fg:"#165344",accent:gold,symbol:"✦",kicker:"فرحة العيد",decor:"gifts"}:design===2?{bg:`linear-gradient(160deg,#fff8ef,#f2e3c7)`,fg:"#4c5a43",accent:gold,symbol:"🎁",kicker:"عيدنا أجمل",decor:"gifts"}:{bg:`linear-gradient(160deg,#073d34,#021f1b)`,fg:"#fff4d4",accent:gold,symbol:"☾",kicker:"عيد سعيد",decor:"moon"};
  if(type==="eid_adha") return design===1?{bg:`linear-gradient(160deg,#fff9eb,#eadcc0)`,fg:"#355145",accent:gold,symbol:"🐑",kicker:"عيد الأضحى",decor:"sheep"}:design===2?{bg:`linear-gradient(160deg,${sand},#f7f1e4)`,fg:"#534634",accent:"#b58a46",symbol:"🐏",kicker:"بهجة الأضحى",decor:"desert"}:{bg:`linear-gradient(160deg,#073d34,#022c25)`,fg:"#fff4d8",accent:gold,symbol:"🐑",kicker:"أضحى مبارك",decor:"sheep"};
  return {bg:"#090909",fg:"#f7f7f7",accent:"#b8b8b8",symbol:"",kicker:"إنا لله وإنا إليه راجعون",decor:"black"};
}

function TemplatePreview({type,design,selected=false,birthDate,eventDate,birthdayAudience="adult"}:{type:OccasionType;design:number;selected?:boolean;birthDate?:string;eventDate?:string;birthdayAudience?:BirthdayAudience}){
  const age=calcAge(birthDate,eventDate); const r=recipe(type,design,birthdayAudience,age); const condolence=type==="condolence";
  const deco = {
    rings:<><div className="absolute bottom-5 left-1/2 h-12 w-20 -translate-x-1/2 rounded-full border-[7px] border-[#d0a04f]/80 rotate-[-12deg]"/><div className="absolute bottom-5 left-[55%] h-12 w-20 -translate-x-1/2 rounded-full border-[7px] border-[#e7c174]/80 rotate-[12deg]"/></>,
    box:<div className="absolute bottom-3 left-1/2 h-16 w-24 -translate-x-1/2 rotate-45 rounded-[16px] border border-[#c8a45e]/70 bg-black/15 shadow-2xl"/>,
    floral:<><div className="absolute -left-5 top-10 h-28 w-28 rounded-full border-[14px] border-[#87a48d]/15"/><div className="absolute -right-8 bottom-4 h-32 w-32 rounded-full border-[16px] border-[#c8a45e]/15"/></>,
    baby:<div className="absolute bottom-5 left-1/2 -translate-x-1/2 text-5xl opacity-70">🧸</div>, cloud:<div className="absolute bottom-5 left-1/2 -translate-x-1/2 text-6xl opacity-55">☁️</div>, cradle:<div className="absolute bottom-5 left-1/2 -translate-x-1/2 text-5xl opacity-65">🛏️</div>,
    cap:<div className="absolute bottom-4 left-1/2 -translate-x-1/2 text-5xl opacity-65">🎓</div>, certificate:<div className="absolute bottom-4 left-1/2 -translate-x-1/2 text-5xl opacity-65">📜</div>, medal:<div className="absolute bottom-4 left-1/2 -translate-x-1/2 text-5xl opacity-65">🏅</div>,
    cake:<div className="absolute bottom-4 left-1/2 -translate-x-1/2 text-5xl opacity-60">🎂</div>, number:<div className="absolute bottom-0 left-1/2 -translate-x-1/2 text-[78px] font-black opacity-[.08]">{age??5}</div>, balloons:<div className="absolute bottom-4 left-1/2 -translate-x-1/2 text-5xl opacity-60">🎈</div>,
    trophy:<div className="absolute bottom-4 left-1/2 -translate-x-1/2 text-5xl opacity-60">🏆</div>, desk:<div className="absolute bottom-4 left-1/2 -translate-x-1/2 text-4xl opacity-60">📖 ✒️</div>, shield:<div className="absolute bottom-4 left-1/2 h-20 w-20 -translate-x-1/2 rounded-[28px_28px_40px_40px] border-4 border-[#c8a45e]/75 bg-black/10"/>,
    leaves:<><div className="absolute left-2 top-12 text-5xl opacity-25">🌿</div><div className="absolute right-1 bottom-8 text-5xl opacity-20">🌿</div></>, light:<div className="absolute -top-10 left-1/2 h-44 w-44 -translate-x-1/2 rounded-full bg-white/55 blur-3xl"/>, minimal:<div className="absolute inset-4 rounded-[28px] border border-[#c8a45e]/30"/>,
    coffee:<div className="absolute bottom-4 left-1/2 -translate-x-1/2 text-5xl opacity-60">☕</div>, table:<div className="absolute bottom-4 left-1/2 -translate-x-1/2 text-4xl opacity-60">☕ 🍽️</div>, night:<><div className="absolute left-4 top-5 text-3xl opacity-70">✦</div><div className="absolute right-4 top-10 text-2xl opacity-60">✦</div><div className="absolute bottom-4 left-1/2 -translate-x-1/2 text-4xl opacity-60">🏮</div></>,
    moon:<div className="absolute bottom-4 left-1/2 -translate-x-1/2 text-5xl opacity-60">🌙</div>, lantern:<div className="absolute bottom-4 left-1/2 -translate-x-1/2 text-5xl opacity-65">🏮</div>, gifts:<div className="absolute bottom-4 left-1/2 -translate-x-1/2 text-5xl opacity-60">🎁</div>, sheep:<div className="absolute bottom-3 left-1/2 -translate-x-1/2 text-5xl opacity-70">🐑</div>, desert:<><div className="absolute bottom-0 h-16 w-full rounded-[50%_50%_0_0] bg-[#bf9657]/20"/><div className="absolute bottom-4 left-1/2 -translate-x-1/2 text-5xl opacity-70">🐏</div></>, black:null,
  }[r.decor];
  return <div style={{background:r.bg,color:r.fg}} className={`relative aspect-[3/5] w-full overflow-hidden rounded-[24px] border shadow-md ${selected?"ring-2 ring-primary ring-offset-2":"border-black/5"}`}>
    {!condolence&&<div className="absolute inset-2 rounded-[18px] border" style={{borderColor:`${r.accent}77`}}/>}
    {deco}
    <div className="relative z-10 flex h-full flex-col items-center px-3 pt-4 text-center">
      {!condolence?<FamilyLogo dark={["wedding:2","promotion:1","promotion:3","ramadan:1","ramadan:3","eid_fitr:3","eid_adha:3","gathering:3"].includes(`${type}:${design}`)}/>:<div className="mt-3 text-[11px] font-bold tracking-wide text-white/70">{r.kicker}</div>}
      <div className="mt-4 text-3xl font-black" style={{color:r.accent}}>{r.symbol}</div>
      <span className="mt-2 text-[9px] font-black opacity-75">{r.kicker}</span>
      <strong className="mt-2 text-[15px] font-black leading-tight">{buildDefaultTitle(type)}</strong>
      {type==="birthday"&&age!==null&&<strong className="mt-1 text-2xl font-black" style={{color:r.accent}}>{age}</strong>}
      <div className="my-3 h-px w-12" style={{backgroundColor:`${r.accent}88`}}/>
      <span className="text-[8px] opacity-70">اسم المناسبة</span><span className="mt-1 text-[8px] opacity-60">التاريخ • الوقت</span><span className="mt-1 text-[8px] opacity-60">الموقع</span>
      {condolence&&<p className="mt-5 px-2 text-[9px] leading-5 text-white/65">نسأل الله أن يتغمد الفقيد بواسع رحمته ومغفرته</p>}
    </div>
    {selected&&<div className="absolute right-2 top-2 z-20 grid size-7 place-items-center rounded-full bg-primary text-white shadow-lg"><Check className="size-4"/></div>}
  </div>;
}

function Stepper({step}:{step:number}){ const labels=["نوع المناسبة","التصميم","التفاصيل","المراجعة"]; return <div className="grid grid-cols-4 gap-2">{labels.map((label,i)=>{const n=i+1,active=step>=n;return <div key={label} className="relative flex flex-col items-center gap-2">{i<3&&<div className={`absolute top-4 right-1/2 h-px w-full ${step>n?"bg-primary":"bg-border"}`}/>}<div className={`relative z-10 grid size-8 place-items-center rounded-full border text-xs font-black ${active?"border-primary bg-primary text-primary-foreground":"border-border bg-card text-muted-foreground"}`}>{step>n?<Check className="size-4"/>:n}</div><span className={`text-[10px] font-bold ${active?"text-primary":"text-muted-foreground"}`}>{label}</span></div>})}</div>; }

function FamilyOccasionsPage(){
  const [occasions,setOccasions]=useState<Occasion[]>([]),[open,setOpen]=useState(false),[editingId,setEditingId]=useState<string|null>(null),[step,setStep]=useState(1);
  const [type,setType]=useState<OccasionType>("wedding"),[design,setDesign]=useState(1),[title,setTitle]=useState(""),[date,setDate]=useState(""),[time,setTime]=useState(""),[location,setLocation]=useState(""),[details,setDetails]=useState(""),[birthDate,setBirthDate]=useState(""),[birthdayAudience,setBirthdayAudience]=useState<BirthdayAudience>("adult");
  useEffect(()=>{try{const raw=localStorage.getItem(STORAGE_KEY);if(raw)setOccasions(JSON.parse(raw));}catch{setOccasions([])}},[]);
  const selectedMeta=useMemo(()=>getTypeMeta(type),[type]);
  function persist(next:Occasion[]){setOccasions(next);localStorage.setItem(STORAGE_KEY,JSON.stringify(next));}
  function reset(){setEditingId(null);setStep(1);setType("wedding");setDesign(1);setTitle("");setDate("");setTime("");setLocation("");setDetails("");setBirthDate("");setBirthdayAudience("adult");}
  function startCreate(){reset();setOpen(true)}
  function startEdit(o:Occasion){setEditingId(o.id);setType(o.type);setDesign(o.design);setTitle(o.title);setDate(o.date);setTime(o.time);setLocation(o.location);setDetails(o.details);setBirthDate(o.birthDate??"");setBirthdayAudience(o.birthdayAudience??"adult");setStep(3);setOpen(true)}
  function chooseType(next:OccasionType){setType(next);setDesign(1);if(!editingId)setTitle(buildDefaultTitle(next));}
  function deleteOccasion(o:Occasion){if(window.confirm(`حذف مناسبة «${o.title}»؟ لا يمكن التراجع عن هذا الإجراء.`))persist(occasions.filter(x=>x.id!==o.id));}
  function saveOccasion(){const next:Occasion={id:editingId??crypto.randomUUID(),type,design,title:title.trim()||buildDefaultTitle(type),date,time,location,details,birthDate:type==="birthday"?birthDate:undefined,birthdayAudience:type==="birthday"?birthdayAudience:undefined};persist(editingId?occasions.map(x=>x.id===editingId?next:x):[next,...occasions]);setOpen(false);setEditingId(null)}
  const previews=Array.from({length:designCount(type)},(_,i)=>i+1);
  return <AppShell><main dir="rtl" className="mx-auto w-full max-w-7xl px-4 pb-28 pt-5 sm:px-6 lg:px-8">
    <section className="overflow-hidden rounded-[32px] border border-border bg-card shadow-sm"><div className="grid min-h-[300px] items-center gap-8 p-7 md:grid-cols-[1fr_.8fr] md:p-10"><div className="order-2 md:order-1"><div className="inline-flex items-center gap-2 rounded-full border border-[color:var(--gold-primary)]/25 bg-[color:var(--gold-primary)]/10 px-3 py-1.5 text-xs font-black text-gold-primary"><Sparkles className="size-4"/> مناسبات العائلة</div><h1 className="mt-4 text-3xl font-black text-primary sm:text-4xl">مناسبات العائلة</h1><p className="mt-3 text-sm font-medium leading-7 text-muted-foreground sm:text-base">اختر المناسبة، ثم اختر أحد التصاميم المعتمدة الخاصة بها.</p><button onClick={startCreate} className="mt-6 inline-flex items-center gap-2 rounded-2xl bg-primary px-5 py-3 text-sm font-black text-primary-foreground shadow-lg"><Plus className="size-4"/> إضافة مناسبة جديدة</button></div><div className="order-1 flex justify-center md:order-2"><div className="grid size-48 place-items-center rounded-[40px] bg-gradient-to-br from-[color:var(--gold-primary)]/15 via-card to-primary/10"><CalendarDays className="size-24 text-gold-primary" strokeWidth={1.1}/></div></div></div></section>
    {occasions.length===0?<section className="mt-6 rounded-[30px] border border-border bg-card px-6 py-12 text-center shadow-sm"><CalendarDays className="mx-auto size-10 text-gold-primary"/><h2 className="mt-5 text-xl font-black">لا توجد مناسبات حتى الآن</h2><p className="mt-2 text-sm text-muted-foreground">أضف مناسبة واختر تصميمها المعتمد.</p></section>:<section className="mt-7"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-xl font-black">المناسبات</h2><p className="mt-1 text-sm text-muted-foreground">المناسبات المضافة مؤخرًا</p></div><button onClick={startCreate} className="inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-xs font-black text-primary-foreground"><Plus className="size-4"/> إضافة</button></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{occasions.map(o=><article key={o.id} className="rounded-[28px] border border-border bg-card p-4 shadow-sm"><div className="grid grid-cols-[92px_1fr] gap-4"><TemplatePreview type={o.type} design={o.design} birthDate={o.birthDate} eventDate={o.date} birthdayAudience={o.birthdayAudience}/><div className="flex min-w-0 flex-col justify-center"><span className="text-[10px] font-black text-gold-primary">{getTypeMeta(o.type).title}</span><h3 className="mt-1 truncate text-lg font-black">{o.title}</h3>{o.date&&<div className="mt-3 flex items-center gap-2 text-xs text-muted-foreground"><CalendarDays className="size-3.5"/>{o.date}{o.time?` • ${o.time}`:""}</div>}{o.location&&<div className="mt-2 flex items-center gap-2 text-xs text-muted-foreground"><MapPin className="size-3.5"/>{o.location}</div>}<div className="mt-4 flex gap-2 border-t border-border pt-3"><button onClick={()=>startEdit(o)} className="inline-flex flex-1 items-center justify-center gap-1 rounded-xl bg-primary/5 px-2 py-2 text-xs font-black text-primary"><Pencil className="size-3.5"/> تعديل</button><button onClick={()=>deleteOccasion(o)} className="inline-flex flex-1 items-center justify-center gap-1 rounded-xl bg-red-500/5 px-2 py-2 text-xs font-black text-red-600"><Trash2 className="size-3.5"/> حذف</button></div></div></div></article>)}</div></section>}
    <button onClick={startCreate} className="fixed bottom-24 left-5 z-30 grid size-14 place-items-center rounded-full bg-primary text-primary-foreground shadow-xl sm:hidden"><Plus className="size-6"/></button>
  </main>
  {open&&<div className="fixed inset-0 z-[120] flex items-end justify-center bg-black/55 backdrop-blur-sm sm:items-center sm:p-5" dir="rtl"><div className="max-h-[94dvh] w-full max-w-3xl overflow-y-auto rounded-t-[32px] bg-card shadow-2xl sm:rounded-[32px]"><div className="sticky top-0 z-20 border-b border-border bg-card/95 px-5 pb-4 pt-5 backdrop-blur"><div className="mb-5 flex items-center justify-between"><button onClick={()=>setOpen(false)} className="grid size-10 place-items-center rounded-full bg-muted"><X className="size-5"/></button><h2 className="text-lg font-black">{editingId?"تعديل المناسبة":"إضافة مناسبة جديدة"}</h2><div className="size-10"/></div><Stepper step={step}/></div><div className="p-5 sm:p-7">
    {step===1&&<div><h3 className="text-center text-xl font-black">اختر نوع المناسبة</h3><div className="mt-6 grid grid-cols-3 gap-3">{TYPE_OPTIONS.map(item=>{const I=item.icon,sel=type===item.key;return <button key={item.key} onClick={()=>chooseType(item.key)} className={`relative flex min-h-[112px] flex-col items-center justify-center gap-3 rounded-[22px] border p-3 ${sel?"border-primary bg-primary/5":"border-border bg-background/50"}`}><I className={`size-8 ${sel?"text-gold-primary":"text-primary"}`} strokeWidth={1.5}/><span className="text-xs font-black">{item.title}</span>{item.designs===1&&<span className="text-[9px] text-muted-foreground">تصميم واحد</span>}</button>})}</div></div>}
    {step===2&&<div><h3 className="text-center text-xl font-black">اختر تصميم بطاقة المناسبة</h3><p className="mt-2 text-center text-sm text-muted-foreground">{selectedMeta.title} — {designCount(type)===1?"التصميم الرسمي المعتمد":"اختر من 3 تصاميم خاصة بالمناسبة"}</p>{type==="birthday"&&<div className="mx-auto mt-5 flex max-w-sm rounded-2xl bg-muted p-1"><button onClick={()=>setBirthdayAudience("adult")} className={`flex-1 rounded-xl px-3 py-2 text-xs font-black ${birthdayAudience==="adult"?"bg-card text-primary shadow":"text-muted-foreground"}`}>كبار / رسمي</button><button onClick={()=>setBirthdayAudience("child")} className={`flex-1 rounded-xl px-3 py-2 text-xs font-black ${birthdayAudience==="child"?"bg-card text-primary shadow":"text-muted-foreground"}`}>طفل</button></div>}<div className={`mx-auto mt-6 grid gap-3 sm:gap-5 ${previews.length===1?"max-w-[220px] grid-cols-1":"grid-cols-3"}`}>{previews.map(v=><button key={v} onClick={()=>setDesign(v)}><TemplatePreview type={type} design={v} selected={design===v} birthDate={birthDate} eventDate={date} birthdayAudience={birthdayAudience}/><span className={`mt-3 block text-xs font-black ${design===v?"text-primary":"text-muted-foreground"}`}>تصميم {v}</span></button>)}</div></div>}
    {step===3&&<div className="grid gap-6 md:grid-cols-[170px_1fr]"><div><TemplatePreview type={type} design={design} selected birthDate={birthDate} eventDate={date} birthdayAudience={birthdayAudience}/><button onClick={()=>setStep(2)} className="mt-3 w-full rounded-xl border border-border px-3 py-2 text-xs font-black text-primary">تغيير التصميم</button></div><div><h3 className="text-xl font-black">تفاصيل المناسبة</h3><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2"><span className="mb-1.5 block text-xs font-black">عنوان المناسبة</span><input value={title} onChange={e=>setTitle(e.target.value)} placeholder={buildDefaultTitle(type)} className="w-full rounded-2xl border border-border bg-background px-4 py-3 text-sm"/></label>{type==="birthday"&&<label className="sm:col-span-2"><span className="mb-1.5 block text-xs font-black">تاريخ الميلاد <span className="font-medium text-muted-foreground">— يحسب العمر تلقائيًا</span></span><input type="date" value={birthDate} onChange={e=>setBirthDate(e.target.value)} className="w-full rounded-2xl border border-border bg-background px-4 py-3 text-sm"/></label>}<label><span className="mb-1.5 block text-xs font-black">التاريخ</span><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="w-full rounded-2xl border border-border bg-background px-4 py-3 text-sm"/></label><label><span className="mb-1.5 block text-xs font-black">الوقت</span><input type="time" value={time} onChange={e=>setTime(e.target.value)} className="w-full rounded-2xl border border-border bg-background px-4 py-3 text-sm"/></label><label className="sm:col-span-2"><span className="mb-1.5 block text-xs font-black">الموقع</span><input value={location} onChange={e=>setLocation(e.target.value)} className="w-full rounded-2xl border border-border bg-background px-4 py-3 text-sm"/></label><label className="sm:col-span-2"><span className="mb-1.5 block text-xs font-black">تفاصيل إضافية</span><textarea value={details} onChange={e=>setDetails(e.target.value)} rows={4} className="w-full resize-none rounded-2xl border border-border bg-background px-4 py-3 text-sm"/></label></div></div></div>}
    {step===4&&<div className="grid gap-6 md:grid-cols-[220px_1fr]"><TemplatePreview type={type} design={design} selected birthDate={birthDate} eventDate={date} birthdayAudience={birthdayAudience}/><div className="rounded-[24px] border border-border bg-background/50 p-5"><span className="text-xs font-black text-gold-primary">{selectedMeta.title}</span><h3 className="mt-2 text-2xl font-black">{title||buildDefaultTitle(type)}</h3>{type==="birthday"&&birthDate&&<p className="mt-2 text-sm font-bold text-primary">العمر: {calcAge(birthDate,date)??"—"}</p>}<div className="mt-5 space-y-3 text-sm text-muted-foreground"><div className="flex items-center gap-2"><CalendarDays className="size-4"/>{date||"لم يحدد التاريخ"}{time?` • ${time}`:""}</div><div className="flex items-center gap-2"><MapPin className="size-4"/>{location||"لم يحدد الموقع"}</div></div>{details&&<p className="mt-5 border-t border-border pt-4 text-sm leading-7 text-muted-foreground">{details}</p>}</div></div>}
    </div><div className="sticky bottom-0 flex gap-3 border-t border-border bg-card/95 p-5 backdrop-blur">{step>1&&<button onClick={()=>setStep(v=>v-1)} className="inline-flex min-w-28 items-center justify-center gap-2 rounded-2xl border border-border px-5 py-3 text-sm font-black"><ChevronRight className="size-4"/> السابق</button>}{step<4?<button onClick={()=>setStep(v=>Math.min(4,v+1))} className="inline-flex flex-1 items-center justify-center gap-2 rounded-2xl bg-primary px-5 py-3 text-sm font-black text-primary-foreground">التالي <ChevronLeft className="size-4"/></button>:<button onClick={saveOccasion} className="inline-flex flex-1 items-center justify-center gap-2 rounded-2xl bg-primary px-5 py-3 text-sm font-black text-primary-foreground"><Check className="size-4"/> {editingId?"حفظ التعديلات":"حفظ المناسبة"}</button>}</div></div></div>}
  </AppShell>;
}
