import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { AppShell } from "@/components/app-shell";
import { Baby,Cake,CalendarDays,Check,ChevronLeft,ChevronRight,Flower2,GraduationCap,Heart,MapPin,MoonStar,Pencil,Plus,ShieldPlus,Sparkles,Trash2,Trophy,Users,X } from "lucide-react";

export const Route=createFileRoute("/_authenticated/family-occasions")({ssr:false,head:()=>({meta:[{title:"مناسبات العائلة — السيف"},{name:"description",content:"مناسبات العائلة ودعواتها في مكان واحد."}]}),component:FamilyOccasionsPage});

type OccasionType="wedding"|"newborn"|"condolence"|"graduation"|"birthday"|"promotion"|"recovery"|"gathering"|"ramadan"|"eid_fitr"|"eid_adha";
type BirthdayAudience="adult"|"child";
type Occasion={id:string;type:OccasionType;design:number;title:string;date:string;time:string;location:string;details:string;birthDate?:string;birthdayAudience?:BirthdayAudience};
type Meta={key:OccasionType;title:string;icon:typeof Heart;designs:number};
const TYPES:Meta[]=[
 {key:"wedding",title:"زواج / ملكة",icon:Heart,designs:3},{key:"newborn",title:"مولود",icon:Baby,designs:3},{key:"graduation",title:"تخرج",icon:GraduationCap,designs:3},{key:"condolence",title:"عزاء",icon:Flower2,designs:1},{key:"birthday",title:"يوم ميلاد",icon:Cake,designs:3},{key:"promotion",title:"ترقية / إنجاز",icon:Trophy,designs:3},{key:"recovery",title:"شفاء / سلامة",icon:ShieldPlus,designs:3},{key:"gathering",title:"عزيمة / لمة عائلية",icon:Users,designs:3},{key:"ramadan",title:"رمضان",icon:MoonStar,designs:3},{key:"eid_fitr",title:"عيد الفطر",icon:Sparkles,designs:3},{key:"eid_adha",title:"عيد الأضحى",icon:MoonStar,designs:3}
];
const COPY:Record<OccasionType,{heading:string;body:string;nameLabel:string;optional?:boolean}>={
 wedding:{heading:"دعوة زواج",body:"بسم الله وعلى بركة الله، وبقلوبٍ يملؤها الفرح والسرور، يسرّنا أن نشارككم أجمل لحظاتنا وأن ندعوكم لمشاركتنا فرحة الزواج. حضوركم بيننا يزيد فرحتنا بهجةً، ويجعل لهذه الليلة ذكرى أجمل. نسأل الله أن يبارك هذا الزواج، وأن يجمع بين الزوجين على المودة والرحمة، وأن يكتب لهما حياةً عامرة بالسعادة والهناء.",nameLabel:"اسم العريس / العروس"},
 newborn:{heading:"بشارة مولود",body:"الحمد لله الذي بنعمته تتم الصالحات، وبفضله تكتمل الأفراح. أكرمنا الله بمولودٍ أضاء دنيانا وزاد بيتنا فرحًا وسعادة. نسأل الله أن ينبته نباتًا حسنًا، وأن يقرّ به أعين والديه، ويحفظه بعينه التي لا تنام، ويجعله من الصالحين المباركين، ويرزقه عمرًا جميلًا مليئًا بالصحة والعافية والخير.",nameLabel:"اسم المولود"},
 graduation:{heading:"مبارك التخرج",body:"بعد أعوامٍ من الجد والاجتهاد، جاء يوم الحصاد لتكتمل فرحة الإنجاز. بكل فخر واعتزاز نبارك هذا التخرج، ونشارككم فرحة خطوةٍ جميلة تفتح أبواب مستقبلٍ مليء بالطموح والنجاح. نسأل الله أن يجعل ما مضى بدايةً لإنجازات أكبر، وأن يكتب للخريج أو الخريجة التوفيق والسداد في كل خطوة قادمة.",nameLabel:"اسم الخريج / الخريجة"},
 condolence:{heading:"إنا لله وإنا إليه راجعون",body:"بقلوبٍ مؤمنة بقضاء الله وقدره، وببالغ الحزن والأسى، ننعى فقيدنا الغالي، سائلين المولى عز وجل أن يتغمّده بواسع رحمته ومغفرته، وأن يجعل قبره روضةً من رياض الجنة، وينوّر له فيه، ويرفع درجته في المهديين، وأن يلهم أهله وذويه الصبر والسلوان. اللهم اغفر له وارحمه واعفُ عنه وأكرم نزله واجمعنا به في جنات النعيم.",nameLabel:"اسم المتوفى"},
 birthday:{heading:"كل عام وأنت بخير",body:"في هذا اليوم الجميل نحتفل بعامٍ جديد من العمر، وبصفحةٍ جديدة نرجو أن تكون مليئة بالفرح والنجاح والذكريات التي تستحق أن تُحفظ. كل عام والقلب أسعد، والأيام أجمل، والأمنيات أقرب. نسأل الله أن يجعل العام القادم عام خير وبركة، وأن يرزق صاحبه الصحة والعافية والسعادة وتحقيق ما يتمنى.",nameLabel:"الاسم"},
 promotion:{heading:"مبارك الإنجاز",body:"لكل مجتهدٍ نصيب، ولكل طريقٍ من العمل والمثابرة لحظةٌ جميلة تُتوّج بالنجاح. بكل فخر نبارك هذا الإنجاز المستحق وهذه الخطوة المميزة، ونسأل الله أن يجعلها بدايةً لمراحل أكبر من التوفيق والتقدم، وأن يبارك في الجهد والعطاء، ويكتب لصاحب الإنجاز مزيدًا من النجاح والتميّز في القادم.",nameLabel:"الاسم"},
 recovery:{heading:"الحمد لله على السلامة",body:"الحمد لله حمدًا كثيرًا على تمام العافية والسلامة، فما بعد التعب أجمل من نعمة الصحة وطمأنينة القلب. نسأل الله أن يجعل ما مضى طهورًا وأجرًا، وأن يتمّ الشفاء على خير، ويلبس صاحب المناسبة لباس الصحة والعافية، ويحفظه من كل سوء، ويديم عليه نعمه وفضله، ويملأ أيامه القادمة راحةً وصحةً وسعادة.",nameLabel:"الاسم"},
 gathering:{heading:"دعوة للّمة العائلية",body:"لأن لَمّة الأهل لها في القلب مكانٌ لا يشبهه شيء، ولأن أجمل الأوقات هي التي تجمعنا بمن نحب، يسعدنا دعوتكم إلى لَمّة عائلية دافئة نلتقي فيها على المحبة والفرح والحديث الجميل. حضوركم هو الذي يكمّل جمعتنا ويزيدها بهجة، ونسعد بقضاء وقتٍ جميل معًا نصنع فيه ذكريات تبقى في القلب.",nameLabel:"اسم صاحب الدعوة",optional:true},
 ramadan:{heading:"رمضان مبارك",body:"بمناسبة حلول شهر رمضان المبارك، شهر الرحمة والمغفرة والعتق من النار، نرفع لكم أصدق التهاني وأطيب الدعوات. نسأل الله أن يبلغنا وإياكم رمضان أعوامًا عديدة وأزمنةً مديدة، وأن يعيننا فيه على الصيام والقيام وصالح الأعمال، ويتقبّل منا ومنكم، ويجعله شهر خير وبركة وطمأنينة، ويكتب لنا ولكم فيه الرحمة والمغفرة والقبول.",nameLabel:"الاسم",optional:true},
 eid_fitr:{heading:"عيد فطر مبارك",body:"بعد أيامٍ مباركة من الصيام والقيام، أقبل عيد الفطر بفرحته الجميلة وبهجته التي تجمع القلوب. تقبّل الله منا ومنكم صالح الأعمال، وأعاد علينا وعليكم هذه الأيام المباركة بالخير واليمن والبركات. نسأل الله أن يجعل عيدكم فرحًا لا ينتهي، وأن يملأ بيوتكم سعادةً وطمأنينة، ويحفظ لكم أحبابكم، وكل عام وأنتم بخير.",nameLabel:"الاسم",optional:true},
 eid_adha:{heading:"عيد أضحى مبارك",body:"بمناسبة عيد الأضحى المبارك، نتقدّم إليكم بأصدق التهاني وأجمل الأمنيات، سائلين الله أن يتقبّل منا ومنكم صالح الأعمال والطاعات، وأن يجعل أيام العيد فرحًا وسرورًا وبركة. أعاده الله علينا وعليكم وعلى من تحبون بالصحة والعافية والأمن والإيمان، وملأ بيوتكم بالمحبة والسعادة، وكل عام وأنتم إلى الله أقرب وبخير.",nameLabel:"الاسم",optional:true}
};
const STORAGE="alsaif:family-occasions",ROOT="/occasion-templates";
const meta=(t:OccasionType)=>TYPES.find(x=>x.key===t)??TYPES[0];
function age(b?:string,d?:string){if(!b)return null;const x=new Date(`${b}T12:00:00`),y=d?new Date(`${d}T12:00:00`):new Date();if(Number.isNaN(x.getTime()))return null;let a=y.getFullYear()-x.getFullYear(),m=y.getMonth()-x.getMonth();if(m<0||(m===0&&y.getDate()<x.getDate()))a--;return Math.max(0,a)}
function path(t:OccasionType,n:number,a:BirthdayAudience="adult"){if(t==="condolence")return `${ROOT}/condolence-1.png.png`;if(t==="wedding")return `${ROOT}/wedding-${n}.png.jpg`;if(t==="birthday"&&a==="child")return `${ROOT}/kids-birthday-${n}.png`;if(t==="gathering")return `${ROOT}/family-gathering-${n}.png`;if(t==="eid_fitr")return `${ROOT}/eid-fitr-${n}.png`;if(t==="eid_adha")return `${ROOT}/eid-adha-${n}.png`;return `${ROOT}/${t}-${n}.png`}
function Preview({type,design,selected=false,birthDate,eventDate,birthdayAudience="adult",name,time,location,show=false}:{type:OccasionType;design:number;selected?:boolean;birthDate?:string;eventDate?:string;birthdayAudience?:BirthdayAudience;name?:string;time?:string;location?:string;show?:boolean}){const c=COPY[type],a=age(birthDate,eventDate),cond=type==="condolence";return <div className={`relative aspect-[3/5] w-full overflow-hidden rounded-[24px] bg-muted shadow-md ${selected?"ring-2 ring-primary ring-offset-2":"border border-border"}`}><img src={path(type,design,birthdayAudience)} className="absolute inset-0 h-full w-full object-cover" alt="قالب المناسبة"/>{!cond&&<div className="absolute left-1/2 top-[7%] z-10 -translate-x-1/2"><div className="grid size-10 place-items-center overflow-hidden rounded-full bg-white/80 p-1 shadow-sm"><img src="/logo-home.png" className="h-full w-full object-contain" alt="شعار العائلة"/></div></div>}{show&&<div className={`absolute inset-x-[8%] top-[20%] z-10 flex min-h-[58%] flex-col items-center justify-center px-3 py-4 text-center ${cond?"text-white":"rounded-[18px] bg-white/60 text-[#183f36] shadow-sm backdrop-blur-[1px]"}`}><strong className="text-[14px] font-black leading-tight">{c.heading}</strong><p className="mt-2 text-[7px] font-bold leading-[13px] opacity-90">{c.body}</p>{name?.trim()&&<strong className="mt-3 text-[13px] font-black">{name}</strong>}{type==="birthday"&&a!==null&&<strong className="mt-2 text-3xl font-black">{a}</strong>}{(eventDate||time)&&<span className="mt-3 text-[9px] font-bold opacity-80">{eventDate||""}{eventDate&&time?" • ":""}{time||""}</span>}{location&&<span className="mt-1 text-[9px] font-bold opacity-75">{location}</span>}</div>}{selected&&<div className="absolute right-2 top-2 z-20 grid size-7 place-items-center rounded-full bg-primary text-white"><Check className="size-4"/></div>}</div>}
function Stepper({step}:{step:number}){return <div className="grid grid-cols-4 gap-2">{["نوع المناسبة","التصميم","البيانات","المراجعة"].map((l,i)=>{const v=i+1,a=step>=v;return <div key={l} className="flex flex-col items-center gap-2"><div className={`grid size-8 place-items-center rounded-full border text-xs font-black ${a?"border-primary bg-primary text-primary-foreground":"border-border bg-card text-muted-foreground"}`}>{step>v?<Check className="size-4"/>:v}</div><span className={`text-[10px] font-bold ${a?"text-primary":"text-muted-foreground"}`}>{l}</span></div>})}</div>}
function FamilyOccasionsPage(){const [items,setItems]=useState<Occasion[]>([]),[open,setOpen]=useState(false),[editing,setEditing]=useState<string|null>(null),[step,setStep]=useState(1),[type,setType]=useState<OccasionType>("wedding"),[design,setDesign]=useState(1),[name,setName]=useState(""),[date,setDate]=useState(""),[time,setTime]=useState(""),[location,setLocation]=useState(""),[birthDate,setBirthDate]=useState(""),[audience,setAudience]=useState<BirthdayAudience>("adult");
 useEffect(()=>{try{const r=localStorage.getItem(STORAGE);if(r)setItems(JSON.parse(r))}catch{}},[]);const selected=useMemo(()=>meta(type),[type]),previews=Array.from({length:selected.designs},(_,i)=>i+1);const persist=(x:Occasion[])=>{setItems(x);localStorage.setItem(STORAGE,JSON.stringify(x))};
 function reset(){setEditing(null);setStep(1);setType("wedding");setDesign(1);setName("");setDate("");setTime("");setLocation("");setBirthDate("");setAudience("adult")}
 function start(){reset();setOpen(true)} function edit(o:Occasion){setEditing(o.id);setType(o.type);setDesign(o.design);setName(o.title||"");setDate(o.date);setTime(o.time);setLocation(o.location);setBirthDate(o.birthDate||"");setAudience(o.birthdayAudience||"adult");setStep(3);setOpen(true)}
 function save(){const o:Occasion={id:editing??crypto.randomUUID(),type,design,title:name.trim(),date,time,location,details:"",birthDate:type==="birthday"?birthDate:undefined,birthdayAudience:type==="birthday"?audience:undefined};persist(editing?items.map(x=>x.id===editing?o:x):[o,...items]);setOpen(false)}
 return <AppShell><main dir="rtl" className="mx-auto w-full max-w-7xl px-4 pb-28 pt-5 sm:px-6 lg:px-8"><section className="overflow-hidden rounded-[32px] border border-border bg-card shadow-sm"><div className="grid min-h-[260px] items-center gap-8 p-7 md:grid-cols-[1fr_.8fr]"><div><div className="inline-flex items-center gap-2 rounded-full bg-[color:var(--gold-primary)]/10 px-3 py-1.5 text-xs font-black text-gold-primary"><Sparkles className="size-4"/> مناسبات العائلة</div><h1 className="mt-4 text-3xl font-black text-primary">مناسبات العائلة</h1><p className="mt-3 text-sm text-muted-foreground">اختر المناسبة والقالب، ثم أدخل البيانات المتغيرة فقط. نص المناسبة جاهز تلقائيًا.</p><button onClick={start} className="mt-6 inline-flex items-center gap-2 rounded-2xl bg-primary px-5 py-3 text-sm font-black text-primary-foreground"><Plus className="size-4"/> إضافة مناسبة جديدة</button></div><div className="hidden justify-center md:flex"><CalendarDays className="size-24 text-gold-primary"/></div></div></section>
 {items.length===0?<section className="mt-6 rounded-[30px] border border-border bg-card px-6 py-12 text-center"><CalendarDays className="mx-auto size-10 text-gold-primary"/><h2 className="mt-5 text-xl font-black">لا توجد مناسبات حتى الآن</h2></section>:<section className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.map(o=><article key={o.id} className="rounded-[28px] border border-border bg-card p-4"><div className="grid grid-cols-[92px_1fr] gap-4"><Preview type={o.type} design={o.design} birthDate={o.birthDate} eventDate={o.date} birthdayAudience={o.birthdayAudience} name={o.title} time={o.time} location={o.location} show/><div className="flex min-w-0 flex-col justify-center"><span className="text-[10px] font-black text-gold-primary">{meta(o.type).title}</span><h3 className="mt-1 truncate text-lg font-black">{o.title||COPY[o.type].heading}</h3>{o.date&&<div className="mt-3 flex items-center gap-2 text-xs text-muted-foreground"><CalendarDays className="size-3.5"/>{o.date}{o.time?` • ${o.time}`:""}</div>}{o.location&&<div className="mt-2 flex items-center gap-2 text-xs text-muted-foreground"><MapPin className="size-3.5"/>{o.location}</div>}<div className="mt-4 flex gap-2 border-t border-border pt-3"><button onClick={()=>edit(o)} className="flex-1 rounded-xl bg-primary/5 py-2 text-xs font-black text-primary"><Pencil className="mx-auto size-3.5"/></button><button onClick={()=>window.confirm("حذف المناسبة؟")&&persist(items.filter(x=>x.id!==o.id))} className="flex-1 rounded-xl bg-red-500/5 py-2 text-red-600"><Trash2 className="mx-auto size-3.5"/></button></div></div></div></article>)}</section>}</main>
 {open&&<div className="fixed inset-0 z-[120] flex items-end justify-center bg-black/55 sm:items-center sm:p-5" dir="rtl"><div className="max-h-[94dvh] w-full max-w-3xl overflow-y-auto rounded-t-[32px] bg-card sm:rounded-[32px]"><div className="sticky top-0 z-20 border-b border-border bg-card/95 px-5 pb-4 pt-5"><div className="mb-5 flex items-center justify-between"><button onClick={()=>setOpen(false)} className="grid size-10 place-items-center rounded-full bg-muted"><X className="size-5"/></button><h2 className="text-lg font-black">{editing?"تعديل المناسبة":"إضافة مناسبة جديدة"}</h2><div className="size-10"/></div><Stepper step={step}/></div><div className="p-5 sm:p-7">
 {step===1&&<div><h3 className="text-center text-xl font-black">اختر نوع المناسبة</h3><div className="mt-6 grid grid-cols-3 gap-3">{TYPES.map(x=>{const I=x.icon;return <button key={x.key} onClick={()=>{setType(x.key);setDesign(1)}} className={`flex min-h-[112px] flex-col items-center justify-center gap-3 rounded-[22px] border p-3 ${type===x.key?"border-primary bg-primary/5":"border-border"}`}><I className="size-8"/><span className="text-xs font-black">{x.title}</span></button>})}</div></div>}
 {step===2&&<div><h3 className="text-center text-xl font-black">اختر تصميم بطاقة المناسبة</h3>{type==="birthday"&&<div className="mx-auto mt-5 flex max-w-sm rounded-2xl bg-muted p-1"><button onClick={()=>setAudience("adult")} className={`flex-1 rounded-xl px-3 py-2 text-xs font-black ${audience==="adult"?"bg-card shadow":""}`}>كبار / رسمي</button><button onClick={()=>setAudience("child")} className={`flex-1 rounded-xl px-3 py-2 text-xs font-black ${audience==="child"?"bg-card shadow":""}`}>طفل</button></div>}<div className={`mx-auto mt-6 grid gap-5 ${previews.length===1?"max-w-[220px] grid-cols-1":"grid-cols-3"}`}>{previews.map(n=><button key={n} onClick={()=>setDesign(n)}><Preview type={type} design={n} selected={design===n} birthdayAudience={audience}/><span className="mt-3 block text-xs font-black">تصميم {n}</span></button>)}</div></div>}
 {step===3&&<div className="grid gap-6 md:grid-cols-[190px_1fr]"><div><Preview type={type} design={design} selected birthDate={birthDate} eventDate={date} birthdayAudience={audience} name={name} time={time} location={location} show/></div><div><h3 className="text-xl font-black">بيانات المناسبة</h3><div className="mt-3 rounded-2xl bg-primary/5 p-4"><strong className="text-sm font-black text-primary">{COPY[type].heading}</strong><p className="mt-1 text-xs leading-6 text-muted-foreground">{COPY[type].body}</p></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2"><span className="mb-1.5 block text-xs font-black">{COPY[type].nameLabel}{COPY[type].optional?" (اختياري)":""}</span><input value={name} onChange={e=>setName(e.target.value)} className="w-full rounded-2xl border border-border bg-background px-4 py-3 text-sm"/></label>{type==="birthday"&&<label className="sm:col-span-2"><span className="mb-1.5 block text-xs font-black">تاريخ الميلاد — يحسب العمر تلقائيًا</span><input type="date" value={birthDate} onChange={e=>setBirthDate(e.target.value)} className="w-full rounded-2xl border border-border bg-background px-4 py-3"/></label>}<label><span className="mb-1.5 block text-xs font-black">التاريخ</span><input type="date" value={date} onChange={e=>setDate(e.target.value)} className="w-full rounded-2xl border border-border bg-background px-4 py-3"/></label><label><span className="mb-1.5 block text-xs font-black">الوقت</span><input type="time" value={time} onChange={e=>setTime(e.target.value)} className="w-full rounded-2xl border border-border bg-background px-4 py-3"/></label><label className="sm:col-span-2"><span className="mb-1.5 block text-xs font-black">الموقع</span><input value={location} onChange={e=>setLocation(e.target.value)} className="w-full rounded-2xl border border-border bg-background px-4 py-3"/></label></div></div></div>}
 {step===4&&<div className="grid gap-6 md:grid-cols-[240px_1fr]"><Preview type={type} design={design} selected birthDate={birthDate} eventDate={date} birthdayAudience={audience} name={name} time={time} location={location} show/><div className="rounded-[24px] border border-border p-5"><span className="text-xs font-black text-gold-primary">{selected.title}</span><h3 className="mt-2 text-2xl font-black">{COPY[type].heading}</h3><p className="mt-3 text-sm leading-7 text-muted-foreground">{COPY[type].body}</p>{name&&<p className="mt-3 font-black">{name}</p>}{type==="birthday"&&birthDate&&<p className="mt-2 text-sm font-bold">العمر: {age(birthDate,date)??"—"}</p>}<div className="mt-5 space-y-3 text-sm text-muted-foreground"><div className="flex items-center gap-2"><CalendarDays className="size-4"/>{date||"لم يحدد التاريخ"}{time?` • ${time}`:""}</div><div className="flex items-center gap-2"><MapPin className="size-4"/>{location||"لم يحدد الموقع"}</div></div></div></div>}</div><div className="sticky bottom-0 flex gap-3 border-t border-border bg-card/95 p-5">{step>1&&<button onClick={()=>setStep(v=>v-1)} className="inline-flex min-w-28 items-center justify-center gap-2 rounded-2xl border border-border px-5 py-3 text-sm font-black"><ChevronRight className="size-4"/> السابق</button>}{step<4?<button onClick={()=>setStep(v=>Math.min(4,v+1))} className="inline-flex flex-1 items-center justify-center gap-2 rounded-2xl bg-primary px-5 py-3 text-sm font-black text-primary-foreground">التالي <ChevronLeft className="size-4"/></button>:<button onClick={save} className="inline-flex flex-1 items-center justify-center gap-2 rounded-2xl bg-primary px-5 py-3 text-sm font-black text-primary-foreground"><Check className="size-4"/> حفظ المناسبة</button>}</div></div></div>}</AppShell>}
