export type MillionaireSpaceKind =
  "start" | "city" | "chance" | "island" | "travel" | "festival" | "tourism";

export type MillionaireSpace = {
  name: string;
  kind: MillionaireSpaceKind;
  price: number;
  rent: number;
  side: 0 | 1 | 2 | 3;
  group?: string;
  color: string;
  landmark?: string;
  build?: readonly [number, number, number, number];
};

export const MILLIONAIRE_BOARD: readonly MillionaireSpace[] = [
  { name: "الانطلاق", kind: "start", price: 0, rent: 0, side: 0, color: "#dfb94f" },
  {
    name: "الدرعية",
    kind: "city",
    price: 220,
    rent: 42,
    side: 0,
    group: "najd",
    color: "#b87936",
    landmark: "حي الطريف",
    build: [90, 150, 230, 360],
  },
  {
    name: "الرياض",
    kind: "city",
    price: 300,
    rent: 58,
    side: 0,
    group: "najd",
    color: "#b87936",
    landmark: "برج المملكة",
    build: [120, 190, 280, 420],
  },
  { name: "بطاقة فرصة", kind: "chance", price: 0, rent: 0, side: 0, color: "#a96ad4" },
  {
    name: "القصيم",
    kind: "city",
    price: 250,
    rent: 48,
    side: 0,
    group: "central",
    color: "#d29d25",
    landmark: "برج بريدة",
    build: [100, 160, 240, 380],
  },
  {
    name: "حائل",
    kind: "city",
    price: 270,
    rent: 52,
    side: 0,
    group: "central",
    color: "#d29d25",
    landmark: "قلعة عيرف",
    build: [110, 170, 260, 400],
  },
  { name: "الجزيرة", kind: "island", price: 0, rent: 0, side: 0, color: "#668a73" },
  {
    name: "تبوك",
    kind: "city",
    price: 320,
    rent: 62,
    side: 1,
    group: "north",
    color: "#5f7fd2",
    landmark: "قلعة تبوك",
    build: [130, 200, 300, 450],
  },
  {
    name: "العلا",
    kind: "tourism",
    price: 420,
    rent: 110,
    side: 1,
    group: "tourism",
    color: "#7e5fc5",
    landmark: "قصر الفريد",
  },
  {
    name: "سكاكا",
    kind: "city",
    price: 340,
    rent: 66,
    side: 1,
    group: "north",
    color: "#5f7fd2",
    landmark: "قلعة زعبل",
    build: [140, 210, 320, 470],
  },
  { name: "بطاقة فرصة", kind: "chance", price: 0, rent: 0, side: 1, color: "#a96ad4" },
  {
    name: "نيوم",
    kind: "city",
    price: 500,
    rent: 96,
    side: 1,
    group: "north",
    color: "#5f7fd2",
    landmark: "ذا لاين",
    build: [190, 290, 430, 620],
  },
  { name: "جولة المملكة", kind: "travel", price: 0, rent: 0, side: 1, color: "#3196a7" },
  {
    name: "جدة",
    kind: "city",
    price: 390,
    rent: 76,
    side: 2,
    group: "west",
    color: "#2e9ab2",
    landmark: "واجهة جدة",
    build: [150, 240, 360, 520],
  },
  {
    name: "مكة",
    kind: "tourism",
    price: 520,
    rent: 140,
    side: 2,
    group: "tourism",
    color: "#b34f5a",
    landmark: "بوابة مكة",
  },
  {
    name: "الطائف",
    kind: "city",
    price: 350,
    rent: 68,
    side: 2,
    group: "west",
    color: "#2e9ab2",
    landmark: "قصر شبرا",
    build: [140, 220, 330, 490],
  },
  { name: "بطاقة فرصة", kind: "chance", price: 0, rent: 0, side: 2, color: "#a96ad4" },
  {
    name: "المدينة",
    kind: "tourism",
    price: 480,
    rent: 128,
    side: 2,
    group: "tourism",
    color: "#b34f5a",
    landmark: "محطة الحجاز",
  },
  { name: "مهرجان المملكة", kind: "festival", price: 0, rent: 0, side: 2, color: "#df9b23" },
  {
    name: "أبها",
    kind: "city",
    price: 360,
    rent: 70,
    side: 3,
    group: "south",
    color: "#4d9c62",
    landmark: "قرية المفتاحة",
    build: [140, 220, 340, 500],
  },
  {
    name: "جازان",
    kind: "city",
    price: 330,
    rent: 64,
    side: 3,
    group: "south",
    color: "#4d9c62",
    landmark: "قلعة الدوسرية",
    build: [130, 210, 310, 470],
  },
  { name: "بطاقة فرصة", kind: "chance", price: 0, rent: 0, side: 3, color: "#a96ad4" },
  {
    name: "الخبر",
    kind: "city",
    price: 410,
    rent: 80,
    side: 3,
    group: "east",
    color: "#d06c52",
    landmark: "برج الماء",
    build: [160, 250, 370, 540],
  },
  {
    name: "الدمام",
    kind: "city",
    price: 440,
    rent: 86,
    side: 3,
    group: "east",
    color: "#d06c52",
    landmark: "جزيرة المرجان",
    build: [170, 260, 390, 560],
  },
] as const;
